version: 2

sources:
  - name: sh_stg
    database: generandidevdb  
    schema: sh_stg  
    tables:
      - name: ds_045409
      - name: subastas_castilla_y_leon_anual
      - name: subastas_galicia_cuadro_apertura
      - name: subastas_galicia_cuadro_resumen
      - name: properties